export const HTTP_STATUS = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER: 500,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const ERROR_CODES = {
  // Body errors
  INVALID_JSON: 'INVALID_JSON',
  JSON_TOO_LARGE: 'JSON_TOO_LARGE',
  TOO_MANY_FIELDS: 'TOO_MANY_FIELDS',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  
  // Validation errors
  ZOD_VALIDATION_ERROR: 'ZOD_VALIDATION_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_FORMAT: 'INVALID_FORMAT',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  
  // Database errors
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  
  // JWT errors
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_NOT_ACTIVE: 'TOKEN_NOT_ACTIVE',
  MISSING_TOKEN: 'MISSING_TOKEN',
  
  // Upload errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  TOO_MANY_FILES: 'TOO_MANY_FILES',
  TOO_MANY_PARTS: 'TOO_MANY_PARTS',
  FIELD_NAME_TOO_LONG: 'FIELD_NAME_TOO_LONG',
  FIELD_VALUE_TOO_LONG: 'FIELD_VALUE_TOO_LONG',
  INVALID_FILE_FIELD: 'INVALID_FILE_FIELD',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  UPLOAD_ERROR: 'UPLOAD_ERROR',
  
  // Network errors
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  CONNECTION_RESET: 'CONNECTION_RESET',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  
  // General
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN: 'UNKNOWN',
} as const;

export const PG_ERROR_CODES = {
  UNIQUE_VIOLATION: '23505',
  FOREIGN_KEY_VIOLATION: '23503',
  NOT_NULL_VIOLATION: '23502',
  CHECK_VIOLATION: '23514',
  INVALID_TEXT_REPRESENTATION: '22P02',
  CONNECTION_EXCEPTION: '08000',
  UNDEFINED_TABLE: '42P01',
  SYNTAX_ERROR: '42601',
  DEADLOCK_DETECTED: '40P01',
  SERIALIZATION_FAILURE: '40001',
} as const;

